//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationWebiste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class childOfFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public childOfFunction()
        {
            this.contraint_account_function_childOfFunction = new HashSet<contraint_account_function_childOfFunction>();
        }
    
        public int ID { get; set; }
        public string ChildOfFunction1 { get; set; }
        public string Title { get; set; }
        public Nullable<byte> Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contraint_account_function_childOfFunction> contraint_account_function_childOfFunction { get; set; }
    }
}
