//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationWebiste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contraint_account_group
    {
        public int ID { get; set; }
        public string Account { get; set; }
        public string Group { get; set; }
    
        public virtual account account1 { get; set; }
        public virtual group group1 { get; set; }
    }
}
