//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationWebiste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contraint_account_function_childOfFunction
    {
        public int ID { get; set; }
        public string Account { get; set; }
        public string Function { get; set; }
        public string ChildOfFunction { get; set; }
    
        public virtual childOfFunction childOfFunction1 { get; set; }
        public virtual function function1 { get; set; }
    }
}
