//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationWebiste.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbContext : DbContext
    {
        public dbContext()
            : base("name=dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<childOfFunction> childOfFunctions { get; set; }
        public virtual DbSet<contraint_account_function_childOfFunction> contraint_account_function_childOfFunction { get; set; }
        public virtual DbSet<contraint_account_group> contraint_account_group { get; set; }
        public virtual DbSet<contraint_group_function_childOfFunction> contraint_group_function_childOfFunction { get; set; }
        public virtual DbSet<Directory_City> Directory_City { get; set; }
        public virtual DbSet<function> functions { get; set; }
        public virtual DbSet<group> groups { get; set; }
    
        public virtual ObjectResult<P_viewMenuPermission_Result> P_viewMenuPermission(string account)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_viewMenuPermission_Result>("P_viewMenuPermission", accountParameter);
        }
    
        public virtual ObjectResult<string> P_viewPagePermission(string account, string function)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var functionParameter = function != null ?
                new ObjectParameter("Function", function) :
                new ObjectParameter("Function", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_viewPagePermission", accountParameter, functionParameter);
        }
    }
}
